//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityAlert.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public int CaseId { get; set; }
        public System.Guid Code { get; set; }
        public int SysCategoryId { get; set; }
        public int SysStatusId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsPublic { get; set; }
        public string Description { get; set; }
        public string StreetName { get; set; }
        public string StreetNo { get; set; }
        public string CityName { get; set; }
        public string Title { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public string ImageName { get; set; }
    
        public virtual SysCategory SysCategory { get; set; }
        public virtual SysStatus SysStatus { get; set; }
    }
}
