//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityAlert.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int ErrorId { get; set; }
        public System.DateTime OccurredOn { get; set; }
        public string Method { get; set; }
        public string Context { get; set; }
        public string FullErrorText { get; set; }
    }
}
