//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityAlert.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysStatus
    {
        public SysStatus()
        {
            this.Cases = new HashSet<Case>();
        }
    
        public int SysStatusId { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
    
        public virtual ICollection<Case> Cases { get; set; }
    }
}
